[2020-07-06 17:58:06,250 INFO] Loading data from /global/cfs/cdirs/atlas/achkodrov/pixel-NN-master/training1.h5
Traceback (most recent call last):
  File "/global/cfs/cdirs/atlas/achkodrov/pixel-NN-master/scripts/run_training.py", line 105, in <module>
    _main()
  File "/global/cfs/cdirs/atlas/achkodrov/pixel-NN-master/scripts/run_training.py", line 66, in _main
    data = h5.File(args.input, 'r')
  File "/usr/common/software/tensorflow/intel-tensorflow/2.2.0-py37/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/common/software/tensorflow/intel-tensorflow/2.2.0-py37/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 524, error message = 'Unknown error 524')
srun: error: nid02243: task 0: Exited with exit code 1
srun: Terminating job step 32304706.0
